# Uncomment this line to define a global platform for your project
platform :ios, '8.0'
# Uncomment this line if you're using Swift
# use_frameworks!

target 'liangyiyouzhi' do
pod 'AFNetworking', '~> 3.0.0-beta.2'
end

target 'liangyiyouzhiTests' do

end

target 'liangyiyouzhiUITests' do

end

